version: '2'
services:
  ingest:
    container_name: twitterstream_ingest
    build: docker/ingest
    hostname: ingest
    links:
      - zookeeper
      - kafka

  aggregation:
    container_name: twitterstream_aggregation
    build: docker/aggregation
    hostname: aggregation
    links:
      - zookeeper
      - kafka
  
  zookeeper:
    container_name: twitterstream_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    container_name: twitterstream_kafka
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092:9092"
    environment:
     KAFKA_CREATE_TOPICS: "tweets:1:1,aggregation:1:1"
     KAFKA_ADVERTISED_HOST_NAME: kafka 
     KAFKA_PORT: 9092
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
